version: 2

jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"

    working_directory: /Users/distiller/project

    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - run: carthage build --platform iOS
      - run: script/test iphonesimulator "platform=iOS Simulator,name=iPhone 6,OS=12.0" Bento
      - run: script/test iphonesimulator "platform=iOS Simulator,name=iPhone 6,OS=12.0" StyleSheets
      - run: script/test iphonesimulator "platform=iOS Simulator,name=iPhone 6,OS=12.0" Example build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
