version: 2

jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"

    working_directory: /Users/distiller/project

    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - run: script/test iphonesimulator "platform=iOS Simulator,name=iPhone 6,OS=11.3" Bento
      - run: script/test iphonesimulator "platform=iOS Simulator,name=iPhone 6,OS=11.3" Example build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
